
title: OMMte
author: "Dermot Harnett"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  defile: ''
  entrezfile: '' 

output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 7
    fig_height: 7


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dev='png')#,out.height='700px')
```


```{r }

  if(!exists('run_go_enrich')) devtools::load_all('/fast_new/work/groups/ag_ohler/dharnet_m/cortexomics/pipeline/rseq/')


  modeldir <- '/fast_new/work/groups/ag_ohler/dharnet_m/cortexomics/pipeline/xtail/OMM_GO'%T>%dir.create(showWarn=F)
  rmdfold <- '/fast_new/work/groups/ag_ohler/dharnet_m/cortexomics/pipeline/rseq/inst/rmd/de/'
  entreztbl <- read_tsv('/fast_new/work/groups/ag_ohler/dharnet_m/Ribo_Lausanne/pipeline/gencode.v24.metadata.EntrezGene.gz',col_names=F)%>%
    set_colnames(c('ensembl_transcript_id','entrez_gene_id'))%>%
    mutate(ensembl_transcript_id=str_replace(ensembl_transcript_id,'\\.\\d+',''))
  gtrmap <-'/fast_new/work/groups/ag_ohler/dharnet_m//Ribo_Lausanne/pipeline//gene_transcript_map.tsv' %>% 
    fread(header=F) %>% 
    set_colnames(c('gene_id','transcript_id'))
  defile <- '/fast_new/work/groups/ag_ohler/dharnet_m/Ribo_Lausanne/pipeline/xtail/xtail_OMM475.txt'
  my_org_eg_db <- 'org.Hs.eg'
  my_contrast_name <- basename(defile)
  defile <- fread(defile)
  

  stopifnot(mean(entreztbl$ensembl_transcript_id%>%is_in(gtrmap$transcript_id)) > 0.9)
  entrezgenetable<-entreztbl%>%left_join(gtrmap,by=c('ensembl_transcript_id'='transcript_id'))%>%distinct(gene_id,entrez_gene_id)

  defile%<>%filter(!str_detect(feature_id,'uORF_'))

  defile <- defile%>%left_join(entrezgenetable,by=c('feature_id'='gene_id'))%>%distinct(feature_id,.keep_all=T)%>%filter(!is.na(entrez_gene_id))

  entrez_sig_vec <- setNames(factor(as.numeric(defile$adj_p_value < 0.05)),defile$entrez_gene_id)
  entrez_sig_vec %<>% .[!is.na(.)]
  entrez_sig_vec %<>% .[!is.na(names(.))]
  entrez_sig_vec%>%table

```

```{r results='asis'}
if (all(levels(entrez_sig_vec) == c(0, 1))) {
   
   # stopifnot(is.numeric(entrez_sig_vec))
  cat(knitr::knit_child(file.path(rmdfold,"all_go.Rmd"),
    quiet = T
  ))
} else{
   cat(knitr::knit_child(
    text = "Since there are no differential regulated genes for this contrast we cannot perform a GO enrichment analysis.",
    quiet = T
  ))
}
```
